export let selectedCountry = [
    { 'value': "AF", 'title': "Afghanistan" },
    { 'value': "AX", 'title': "Aland Islands"},
    { 'value': "AL", 'title': "Albania", 'selected' : true},
    { 'value': "DZ", 'title': "Algeria" },
    { 'value': "AS", 'title': "American Samoa" },
    { 'value': "AD", 'title': "Andorra", 'selected' : true },
    { 'value': "AO", 'title': "Angola" },
    { 'value': "AI", 'title': "Anguilla" },
    { 'value': "AQ", 'title': "Antarctica" },
    { 'value': "AG", 'title': "Antigua & Barbuda" },
    { 'value': "AR", 'title': "Argentina" },
    { 'value': "AM", 'title': "Armenia" },
    { 'value': "AW", 'title': "Aruba" },
    { 'value': "AU", 'title': "Australia" },
    { 'value': "AT", 'title': "Austria" },
    { 'value': "AZ", 'title': "Azerbaijan" },
    { 'value': "BS", 'title': "Bahamas" },
    { 'value': "BH", 'title': "Bahrain" },
    { 'value': "BD", 'title': "Bangladesh" },
    { 'value': "BB", 'title': "Barbados" },
    { 'value': "BY", 'title': "Belarus" },
    { 'value': "BE", 'title': "Belgium" },
    { 'value': "BZ", 'title': "Belize" },
    { 'value': "BJ", 'title': "Benin" },
    { 'value': "BM", 'title': "Bermuda" },
    { 'value': "BT", 'title': "Bhutan" },
    { 'value': "BO", 'title': "Bolivia" },
    { 'value': "BA", 'title': "Bosnia & Herzegovina" },
    { 'value': "BW", 'title': "Botswana" },
    { 'value': "BV", 'title': "Bouvet Island" },
    { 'value': "BR", 'title': "Brazil" },
    { 'value': "IO", 'title': "British Indian Ocean Territory" },
    { 'value': "VG", 'title': "British Virgin Islands" },
    { 'value': "BN", 'title': "Brunei" },
    { 'value': "BG", 'title': "Bulgaria" },
    { 'value': "BF", 'title': "Burkina Faso" },
    { 'value': "BI", 'title': "Burundi" },
    { 'value': "KH", 'title': "Cambodia" },
    { 'value': "CM", 'title': "Cameroon" },
    { 'value': "CA", 'title': "Canada" },
    { 'value': "CV", 'title': "Cape Verde" },
    { 'value': "BQ", 'title': "Caribbean Netherlands" },
    { 'value': "KY", 'title': "Cayman Islands" },
    { 'value': "CF", 'title': "Central African Republic" },
    { 'value': "TD", 'title': "Chad" },
    { 'value': "CL", 'title': "Chile" },
    { 'value': "CN", 'title': "China" },
    { 'value': "CX", 'title': "Christmas Island" },
    { 'value': "CC", 'title': "Cocos (Keeling) Islands" },
    { 'value': "CO", 'title': "Colombia" },
    { 'value': "KM", 'title': "Comoros" },
    { 'value': "CG", 'title': "Congo - Brazzaville" },
    { 'value': "CD", 'title': "Congo - Kinshasa" },
    { 'value': "CK", 'title': "Cook Islands" },
    { 'value': "CR", 'title': "Costa Rica" },
    { 'value': "CI", 'title': "C\u00f4te d\u2019Ivoire" },
    { 'value': "HR", 'title': "Croatia" },
    { 'value': "CU", 'title': "Cuba" },
    { 'value': "CW", 'title': "Cura\u00e7ao" },
    { 'value': "CY", 'title': "Cyprus" },
    { 'value': "CZ", 'title': "Czechia" },
    { 'value': "DK", 'title': "Denmark" },
    { 'value': "DJ", 'title': "Djibouti" },
    { 'value': "DM", 'title': "Dominica" },
    { 'value': "DO", 'title': "Dominican Republic" },
    { 'value': "EC", 'title': "Ecuador" },
    { 'value': "EG", 'title': "Egypt" },
    { 'value': "SV", 'title': "El Salvador" },
    { 'value': "GQ", 'title': "Equatorial Guinea" },
    { 'value': "ER", 'title': "Eritrea" },
    { 'value': "EE", 'title': "Estonia" },
    { 'value': "SZ", 'title': "Eswatini" },
    { 'value': "ET", 'title': "Ethiopia" },
    { 'value': "FK", 'title': "Falkland Islands" },
    { 'value': "FO", 'title': "Faroe Islands" },
    { 'value': "FJ", 'title': "Fiji" },
    { 'value': "FI", 'title': "Finland" },
    { 'value': "FR", 'title': "France" },
    { 'value': "GF", 'title': "French Guiana" },
    { 'value': "PF", 'title': "French Polynesia" },
    { 'value': "TF", 'title': "French Southern Territories" },
    { 'value': "GA", 'title': "Gabon" },
    { 'value': "GM", 'title': "Gambia" },
    { 'value': "GE", 'title': "Georgia" },
    { 'value': "DE", 'title': "Germany" },
    { 'value': "GH", 'title': "Ghana" },
    { 'value': "GI", 'title': "Gibraltar" },
    { 'value': "GR", 'title': "Greece" },
    { 'value': "GL", 'title': "Greenland" },
    { 'value': "GD", 'title': "Grenada" },
    { 'value': "GP", 'title': "Guadeloupe" },
    { 'value': "GU", 'title': "Guam" },
    { 'value': "GT", 'title': "Guatemala" },
    { 'value': "GG", 'title': "Guernsey" },
    { 'value': "GN", 'title': "Guinea" },
    { 'value': "GW", 'title': "Guinea-Bissau" },
    { 'value': "GY", 'title': "Guyana" },
    { 'value': "HT", 'title': "Haiti" },
    { 'value': "HM", 'title': "Heard & McDonald Islands" },
    { 'value': "HN", 'title': "Honduras" },
    { 'value': "HK", 'title': "Hong Kong SAR China" },
    { 'value': "HU", 'title': "Hungary" },
    { 'value': "IS", 'title': "Iceland" },
    { 'value': "IN", 'title': "India" },
    { 'value': "ID", 'title': "Indonesia" },
    { 'value': "IR", 'title': "Iran" },
    { 'value': "IQ", 'title': "Iraq" },
    { 'value': "IE", 'title': "Ireland" },
    { 'value': "IM", 'title': "Isle of Man" },
    { 'value': "IL", 'title': "Israel" },
    { 'value': "IT", 'title': "Italy" },
    { 'value': "JM", 'title': "Jamaica" },
    { 'value': "JP", 'title': "Japan" },
    { 'value': "JE", 'title': "Jersey" },
    { 'value': "JO", 'title': "Jordan" },
    { 'value': "KZ", 'title': "Kazakhstan" },
    { 'value': "KE", 'title': "Kenya" },
    { 'value': "KI", 'title': "Kiribati" },
    { 'value': "KW", 'title': "Kuwait" },
    { 'value': "KG", 'title': "Kyrgyzstan" },
    { 'value': "LA", 'title': "Laos" },
    { 'value': "LV", 'title': "Latvia" },
    { 'value': "LB", 'title': "Lebanon" },
    { 'value': "LS", 'title': "Lesotho" },
    { 'value': "LR", 'title': "Liberia" },
    { 'value': "LY", 'title': "Libya" },
    { 'value': "LI", 'title': "Liechtenstein" },
    { 'value': "LT", 'title': "Lithuania" },
    { 'value': "LU", 'title': "Luxembourg" },
    { 'value': "MO", 'title': "Macao SAR China" },
    { 'value': "MG", 'title': "Madagascar" },
    { 'value': "MW", 'title': "Malawi" },
    { 'value': "MY", 'title': "Malaysia" },
    { 'value': "MV", 'title': "Maldives" },
    { 'value': "ML", 'title': "Mali" },
    { 'value': "MT", 'title': "Malta" },
    { 'value': "MH", 'title': "Marshall Islands" },
    { 'value': "MQ", 'title': "Martinique" },
    { 'value': "MR", 'title': "Mauritania" },
    { 'value': "MU", 'title': "Mauritius" },
    { 'value': "YT", 'title': "Mayotte" },
    { 'value': "MX", 'title': "Mexico" },
    { 'value': "FM", 'title': "Micronesia" },
    { 'value': "MD", 'title': "Moldova" },
    { 'value': "MC", 'title': "Monaco" },
    { 'value': "MN", 'title': "Mongolia" },
    { 'value': "ME", 'title': "Montenegro" },
    { 'value': "MS", 'title': "Montserrat" },
    { 'value': "MA", 'title': "Morocco" },
    { 'value': "MZ", 'title': "Mozambique" },
    { 'value': "MM", 'title': "Myanmar (Burma)" },
    { 'value': "NA", 'title': "Namibia" },
    { 'value': "NR", 'title': "Nauru" },
    { 'value': "NP", 'title': "Nepal" },
    { 'value': "NL", 'title': "Netherlands" },
    { 'value': "NC", 'title': "New Caledonia" },
    { 'value': "NZ", 'title': "New Zealand" },
    { 'value': "NI", 'title': "Nicaragua" },
    { 'value': "NE", 'title': "Niger" },
    { 'value': "NG", 'title': "Nigeria" },
    { 'value': "NU", 'title': "Niue" },
    { 'value': "NF", 'title': "Norfolk Island" },
    { 'value': "KP", 'title': "North Korea" },
    { 'value': "MK", 'title': "North Macedonia" },
    { 'value': "MP", 'title': "Northern Mariana Islands" },
    { 'value': "NO", 'title': "Norway" },
    { 'value': "OM", 'title': "Oman" },
    { 'value': "PK", 'title': "Pakistan" },
    { 'value': "PW", 'title': "Palau" },
    { 'value': "PS", 'title': "Palestinian Territories" },
    { 'value': "PA", 'title': "Panama" },
    { 'value': "PG", 'title': "Papua New Guinea" },
    { 'value': "PY", 'title': "Paraguay" },
    { 'value': "PE", 'title': "Peru" },
    { 'value': "PH", 'title': "Philippines" },
    { 'value': "PN", 'title': "Pitcairn Islands" },
    { 'value': "PL", 'title': "Poland" },
    { 'value': "PT", 'title': "Portugal" },
    { 'value': "PR", 'title': "Puerto Rico" },
    { 'value': "QA", 'title': "Qatar" },
    { 'value': "RE", 'title': "R\u00e9union" },
    { 'value': "RO", 'title': "Romania" },
    { 'value': "RU", 'title': "Russia" },
    { 'value': "RW", 'title': "Rwanda" },
    { 'value': "WS", 'title': "Samoa" },
    { 'value': "SM", 'title': "San Marino" },
    { 'value': "ST", 'title': "S\u00e3o Tom\u00e9 & Pr\u00edncipe" },
    { 'value': "SA", 'title': "Saudi Arabia" },
    { 'value': "SN", 'title': "Senegal" },
    { 'value': "RS", 'title': "Serbia" },
    { 'value': "SC", 'title': "Seychelles" },
    { 'value': "SL", 'title': "Sierra Leone" },
    { 'value': "SG", 'title': "Singapore" },
    { 'value': "SX", 'title': "Sint Maarten" },
    { 'value': "SK", 'title': "Slovakia" },
    { 'value': "SI", 'title': "Slovenia" },
    { 'value': "SB", 'title': "Solomon Islands" },
    { 'value': "SO", 'title': "Somalia" },
    { 'value': "ZA", 'title': "South Africa" },
    { 'value': "GS", 'title': "South Georgia & South Sandwich Islands" },
    { 'value': "KR", 'title': "South Korea" },
    { 'value': "SS", 'title': "South Sudan" },
    { 'value': "ES", 'title': "Spain" },
    { 'value': "LK", 'title': "Sri Lanka" },
    { 'value': "BL", 'title': "St. Barth\u00e9lemy" },
    { 'value': "SH", 'title': "St. Helena" },
    { 'value': "KN", 'title': "St. Kitts & Nevis" },
    { 'value': "LC", 'title': "St. Lucia" },
    { 'value': "MF", 'title': "St. Martin" },
    { 'value': "PM", 'title': "St. Pierre & Miquelon" },
    { 'value': "VC", 'title': "St. Vincent & Grenadines" },
    { 'value': "SD", 'title': "Sudan" },
    { 'value': "SR", 'title': "Suriname" },
    { 'value': "SJ", 'title': "Svalbard & Jan Mayen" },
    { 'value': "SE", 'title': "Sweden" },
    { 'value': "CH", 'title': "Switzerland" },
    { 'value': "SY", 'title': "Syria" },
    { 'value': "TW", 'title': "Taiwan" },
    { 'value': "TJ", 'title': "Tajikistan" },
    { 'value': "TZ", 'title': "Tanzania" },
    { 'value': "TH", 'title': "Thailand" },
    { 'value': "TL", 'title': "Timor-Leste" },
    { 'value': "TG", 'title': "Togo" },
    { 'value': "TK", 'title': "Tokelau" },
    { 'value': "TO", 'title': "Tonga" },
    { 'value': "TT", 'title': "Trinidad & Tobago" },
    { 'value': "TN", 'title': "Tunisia" },
    { 'value': "TR", 'title': "Turkey" },
    { 'value': "TM", 'title': "Turkmenistan" },
    { 'value': "TC", 'title': "Turks & Caicos Islands" },
    { 'value': "TV", 'title': "Tuvalu" },
    { 'value': "UM", 'title': "U.S. Outlying Islands" },
    { 'value': "VI", 'title': "U.S. Virgin Islands" },
    { 'value': "UG", 'title': "Uganda" },
    { 'value': "UA", 'title': "Ukraine" },
    { 'value': "AE", 'title': "United Arab Emirates" },
    { 'value': "GB", 'title': "United Kingdom" },
    { 'value': "US", 'title': "United States" },
    { 'value': "UY", 'title': "Uruguay" },
    { 'value': "UZ", 'title': "Uzbekistan" },
    { 'value': "VU", 'title': "Vanuatu" },
    { 'value': "VA", 'title': "Vatican City" },
    { 'value': "VE", 'title': "Venezuela" },
    { 'value': "VN", 'title': "Vietnam" },
    { 'value': "WF", 'title': "Wallis & Futuna" },
    { 'value': "EH", 'title': "Western Sahara" },
    { 'value': "YE", 'title': "Yemen" },
    { 'value': "ZM", 'title': "Zambia" },
    { 'value': "ZW", 'title': "Zimbabwe" },
];

export let countries = [
    { 'value': "AF", 'title': "Afghanistan" },
    { 'value': "AX", 'title': "\u00c5land Islands" },
    { 'value': "AL", 'title': "Albania" },
    { 'value': "DZ", 'title': "Algeria" },
    { 'value': "AS", 'title': "American Samoa" },
    { 'value': "AD", 'title': "Andorra" },
    { 'value': "AO", 'title': "Angola" },
    { 'value': "AI", 'title': "Anguilla" },
    { 'value': "AQ", 'title': "Antarctica" },
    { 'value': "AG", 'title': "Antigua & Barbuda" },
    { 'value': "AR", 'title': "Argentina" },
    { 'value': "AM", 'title': "Armenia" },
    { 'value': "AW", 'title': "Aruba" },
    { 'value': "AU", 'title': "Australia" },
    { 'value': "AT", 'title': "Austria" },
    { 'value': "AZ", 'title': "Azerbaijan" },
    { 'value': "BS", 'title': "Bahamas" },
    { 'value': "BH", 'title': "Bahrain" },
    { 'value': "BD", 'title': "Bangladesh"},
    { 'value': "BB", 'title': "Barbados" },
    { 'value': "BY", 'title': "Belarus" },
    { 'value': "BE", 'title': "Belgium" },
    { 'value': "BZ", 'title': "Belize" },
    { 'value': "BJ", 'title': "Benin" },
    { 'value': "BM", 'title': "Bermuda" },
    { 'value': "BT", 'title': "Bhutan" },
    { 'value': "BO", 'title': "Bolivia" },
    { 'value': "BA", 'title': "Bosnia & Herzegovina" },
    { 'value': "BW", 'title': "Botswana" },
    { 'value': "BV", 'title': "Bouvet Island" },
    { 'value': "BR", 'title': "Brazil" },
    { 'value': "IO", 'title': "British Indian Ocean Territory" },
    { 'value': "VG", 'title': "British Virgin Islands" },
    { 'value': "BN", 'title': "Brunei" },
    { 'value': "BG", 'title': "Bulgaria" },
    { 'value': "BF", 'title': "Burkina Faso" },
    { 'value': "BI", 'title': "Burundi" },
    { 'value': "KH", 'title': "Cambodia" },
    { 'value': "CM", 'title': "Cameroon" },
    { 'value': "CA", 'title': "Canada" },
    { 'value': "CV", 'title': "Cape Verde" },
    { 'value': "BQ", 'title': "Caribbean Netherlands" },
    { 'value': "KY", 'title': "Cayman Islands" },
    { 'value': "CF", 'title': "Central African Republic" },
    { 'value': "TD", 'title': "Chad" },
    { 'value': "CL", 'title': "Chile" },
    { 'value': "CN", 'title': "China" },
    { 'value': "CX", 'title': "Christmas Island" },
    { 'value': "CC", 'title': "Cocos (Keeling) Islands" },
    { 'value': "CO", 'title': "Colombia" },
    { 'value': "KM", 'title': "Comoros" },
    { 'value': "CG", 'title': "Congo - Brazzaville" },
    { 'value': "CD", 'title': "Congo - Kinshasa" },
    { 'value': "CK", 'title': "Cook Islands" },
    { 'value': "CR", 'title': "Costa Rica" },
    { 'value': "CI", 'title': "C\u00f4te d\u2019Ivoire" },
    { 'value': "HR", 'title': "Croatia" },
    { 'value': "CU", 'title': "Cuba" },
    { 'value': "CW", 'title': "Cura\u00e7ao" },
    { 'value': "CY", 'title': "Cyprus" },
    { 'value': "CZ", 'title': "Czechia" },
    { 'value': "DK", 'title': "Denmark" },
    { 'value': "DJ", 'title': "Djibouti" },
    { 'value': "DM", 'title': "Dominica" },
    { 'value': "DO", 'title': "Dominican Republic" },
    { 'value': "EC", 'title': "Ecuador" },
    { 'value': "EG", 'title': "Egypt" },
    { 'value': "SV", 'title': "El Salvador" },
    { 'value': "GQ", 'title': "Equatorial Guinea" },
    { 'value': "ER", 'title': "Eritrea" },
    { 'value': "EE", 'title': "Estonia" },
    { 'value': "SZ", 'title': "Eswatini" },
    { 'value': "ET", 'title': "Ethiopia" },
    { 'value': "FK", 'title': "Falkland Islands" },
    { 'value': "FO", 'title': "Faroe Islands" },
    { 'value': "FJ", 'title': "Fiji" },
    { 'value': "FI", 'title': "Finland" },
    { 'value': "FR", 'title': "France" },
    { 'value': "GF", 'title': "French Guiana" },
    { 'value': "PF", 'title': "French Polynesia" },
    { 'value': "TF", 'title': "French Southern Territories" },
    { 'value': "GA", 'title': "Gabon" },
    { 'value': "GM", 'title': "Gambia" },
    { 'value': "GE", 'title': "Georgia" },
    { 'value': "DE", 'title': "Germany" },
    { 'value': "GH", 'title': "Ghana" },
    { 'value': "GI", 'title': "Gibraltar" },
    { 'value': "GR", 'title': "Greece" },
    { 'value': "GL", 'title': "Greenland" },
    { 'value': "GD", 'title': "Grenada" },
    { 'value': "GP", 'title': "Guadeloupe" },
    { 'value': "GU", 'title': "Guam" },
    { 'value': "GT", 'title': "Guatemala" },
    { 'value': "GG", 'title': "Guernsey" },
    { 'value': "GN", 'title': "Guinea" },
    { 'value': "GW", 'title': "Guinea-Bissau" },
    { 'value': "GY", 'title': "Guyana" },
    { 'value': "HT", 'title': "Haiti" },
    { 'value': "HM", 'title': "Heard & McDonald Islands" },
    { 'value': "HN", 'title': "Honduras" },
    { 'value': "HK", 'title': "Hong Kong SAR China" },
    { 'value': "HU", 'title': "Hungary" },
    { 'value': "IS", 'title': "Iceland" },
    { 'value': "IN", 'title': "India" },
    { 'value': "ID", 'title': "Indonesia" },
    { 'value': "IR", 'title': "Iran" },
    { 'value': "IQ", 'title': "Iraq" },
    { 'value': "IE", 'title': "Ireland" },
    { 'value': "IM", 'title': "Isle of Man" },
    { 'value': "IL", 'title': "Israel" },
    { 'value': "IT", 'title': "Italy" },
    { 'value': "JM", 'title': "Jamaica" },
    { 'value': "JP", 'title': "Japan" },
    { 'value': "JE", 'title': "Jersey" },
    { 'value': "JO", 'title': "Jordan" },
    { 'value': "KZ", 'title': "Kazakhstan" },
    { 'value': "KE", 'title': "Kenya" },
    { 'value': "KI", 'title': "Kiribati" },
    { 'value': "KW", 'title': "Kuwait" },
    { 'value': "KG", 'title': "Kyrgyzstan" },
    { 'value': "LA", 'title': "Laos" },
    { 'value': "LV", 'title': "Latvia" },
    { 'value': "LB", 'title': "Lebanon" },
    { 'value': "LS", 'title': "Lesotho" },
    { 'value': "LR", 'title': "Liberia" },
    { 'value': "LY", 'title': "Libya" },
    { 'value': "LI", 'title': "Liechtenstein" },
    { 'value': "LT", 'title': "Lithuania" },
    { 'value': "LU", 'title': "Luxembourg" },
    { 'value': "MO", 'title': "Macao SAR China" },
    { 'value': "MG", 'title': "Madagascar" },
    { 'value': "MW", 'title': "Malawi" },
    { 'value': "MY", 'title': "Malaysia" },
    { 'value': "MV", 'title': "Maldives" },
    { 'value': "ML", 'title': "Mali" },
    { 'value': "MT", 'title': "Malta" },
    { 'value': "MH", 'title': "Marshall Islands" },
    { 'value': "MQ", 'title': "Martinique" },
    { 'value': "MR", 'title': "Mauritania" },
    { 'value': "MU", 'title': "Mauritius" },
    { 'value': "YT", 'title': "Mayotte" },
    { 'value': "MX", 'title': "Mexico" },
    { 'value': "FM", 'title': "Micronesia" },
    { 'value': "MD", 'title': "Moldova" },
    { 'value': "MC", 'title': "Monaco" },
    { 'value': "MN", 'title': "Mongolia" },
    { 'value': "ME", 'title': "Montenegro" },
    { 'value': "MS", 'title': "Montserrat" },
    { 'value': "MA", 'title': "Morocco" },
    { 'value': "MZ", 'title': "Mozambique" },
    { 'value': "MM", 'title': "Myanmar (Burma)" },
    { 'value': "NA", 'title': "Namibia" },
    { 'value': "NR", 'title': "Nauru" },
    { 'value': "NP", 'title': "Nepal" },
    { 'value': "NL", 'title': "Netherlands" },
    { 'value': "NC", 'title': "New Caledonia" },
    { 'value': "NZ", 'title': "New Zealand" },
    { 'value': "NI", 'title': "Nicaragua" },
    { 'value': "NE", 'title': "Niger" },
    { 'value': "NG", 'title': "Nigeria" },
    { 'value': "NU", 'title': "Niue" },
    { 'value': "NF", 'title': "Norfolk Island" },
    { 'value': "KP", 'title': "North Korea" },
    { 'value': "MK", 'title': "North Macedonia" },
    { 'value': "MP", 'title': "Northern Mariana Islands" },
    { 'value': "NO", 'title': "Norway" },
    { 'value': "OM", 'title': "Oman" },
    { 'value': "PK", 'title': "Pakistan" },
    { 'value': "PW", 'title': "Palau" },
    { 'value': "PS", 'title': "Palestinian Territories" },
    { 'value': "PA", 'title': "Panama" },
    { 'value': "PG", 'title': "Papua New Guinea" },
    { 'value': "PY", 'title': "Paraguay" },
    { 'value': "PE", 'title': "Peru" },
    { 'value': "PH", 'title': "Philippines" },
    { 'value': "PN", 'title': "Pitcairn Islands" },
    { 'value': "PL", 'title': "Poland" },
    { 'value': "PT", 'title': "Portugal" },
    { 'value': "PR", 'title': "Puerto Rico" },
    { 'value': "QA", 'title': "Qatar" },
    { 'value': "RE", 'title': "R\u00e9union" },
    { 'value': "RO", 'title': "Romania" },
    { 'value': "RU", 'title': "Russia" },
    { 'value': "RW", 'title': "Rwanda" },
    { 'value': "WS", 'title': "Samoa" },
    { 'value': "SM", 'title': "San Marino" },
    { 'value': "ST", 'title': "S\u00e3o Tom\u00e9 & Pr\u00edncipe" },
    { 'value': "SA", 'title': "Saudi Arabia" },
    { 'value': "SN", 'title': "Senegal" },
    { 'value': "RS", 'title': "Serbia" },
    { 'value': "SC", 'title': "Seychelles" },
    { 'value': "SL", 'title': "Sierra Leone" },
    { 'value': "SG", 'title': "Singapore" },
    { 'value': "SX", 'title': "Sint Maarten" },
    { 'value': "SK", 'title': "Slovakia" },
    { 'value': "SI", 'title': "Slovenia" },
    { 'value': "SB", 'title': "Solomon Islands" },
    { 'value': "SO", 'title': "Somalia" },
    { 'value': "ZA", 'title': "South Africa" },
    { 'value': "GS", 'title': "South Georgia & South Sandwich Islands" },
    { 'value': "KR", 'title': "South Korea" },
    { 'value': "SS", 'title': "South Sudan" },
    { 'value': "ES", 'title': "Spain" },
    { 'value': "LK", 'title': "Sri Lanka" },
    { 'value': "BL", 'title': "St. Barth\u00e9lemy" },
    { 'value': "SH", 'title': "St. Helena" },
    { 'value': "KN", 'title': "St. Kitts & Nevis" },
    { 'value': "LC", 'title': "St. Lucia" },
    { 'value': "MF", 'title': "St. Martin" },
    { 'value': "PM", 'title': "St. Pierre & Miquelon" },
    { 'value': "VC", 'title': "St. Vincent & Grenadines" },
    { 'value': "SD", 'title': "Sudan" },
    { 'value': "SR", 'title': "Suriname" },
    { 'value': "SJ", 'title': "Svalbard & Jan Mayen" },
    { 'value': "SE", 'title': "Sweden" },
    { 'value': "CH", 'title': "Switzerland" },
    { 'value': "SY", 'title': "Syria" },
    { 'value': "TW", 'title': "Taiwan" },
    { 'value': "TJ", 'title': "Tajikistan" },
    { 'value': "TZ", 'title': "Tanzania" },
    { 'value': "TH", 'title': "Thailand" },
    { 'value': "TL", 'title': "Timor-Leste" },
    { 'value': "TG", 'title': "Togo" },
    { 'value': "TK", 'title': "Tokelau" },
    { 'value': "TO", 'title': "Tonga" },
    { 'value': "TT", 'title': "Trinidad & Tobago" },
    { 'value': "TN", 'title': "Tunisia" },
    { 'value': "TR", 'title': "Turkey" },
    { 'value': "TM", 'title': "Turkmenistan" },
    { 'value': "TC", 'title': "Turks & Caicos Islands" },
    { 'value': "TV", 'title': "Tuvalu" },
    { 'value': "UM", 'title': "U.S. Outlying Islands" },
    { 'value': "VI", 'title': "U.S. Virgin Islands" },
    { 'value': "UG", 'title': "Uganda" },
    { 'value': "UA", 'title': "Ukraine" },
    { 'value': "AE", 'title': "United Arab Emirates" },
    { 'value': "GB", 'title': "United Kingdom" },
    { 'value': "US", 'title': "United States" },
    { 'value': "UY", 'title': "Uruguay" },
    { 'value': "UZ", 'title': "Uzbekistan" },
    { 'value': "VU", 'title': "Vanuatu" },
    { 'value': "VA", 'title': "Vatican City" },
    { 'value': "VE", 'title': "Venezuela" },
    { 'value': "VN", 'title': "Vietnam" },
    { 'value': "WF", 'title': "Wallis & Futuna" },
    { 'value': "EH", 'title': "Western Sahara" },
    { 'value': "YE", 'title': "Yemen" },
    { 'value': "ZM", 'title': "Zambia" },
    { 'value': "ZW", 'title': "Zimbabwe" },
];

export let lang = [
    { 'value': "html", 'title': "html" },
    { 'value': "css", 'title': "css" },
    { 'value': "js", 'title': "js" },
    { 'value': "react", 'title': "react" },
    { 'value': "vue", 'title': "vue" },
]